project:
  type: website
  output-dir: _build
  resources:
    - examples/single-page
    - examples/pkgdown
    - examples/auto-package

metadata-files:
  - api/_sidebar.yml

filters:
  - "interlinks"

interlinks:
  sources:
    python:
      url: https://docs.python.org/3/
    griffe:
      url: https://mkdocstrings.github.io/griffe/

website:
  title: "quartodoc"
  page-navigation: true
  navbar:
    left:
      - file: get-started/overview.qmd
        text: Get Started
      - file: examples/
        text: Examples
      - file: tutorials/
        text: Tutorials
      - href: api/
        text: Reference

    right:
      - icon: github
        href: https://github.com/machow/quartodoc/


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


quartodoc:
  dir: api
  package: quartodoc
  sidebar: "api/_sidebar.yml"
  sections:
    - title: Docstring Renderers
      options:
        dynamic: true
      contents:
        - name: MdRenderer
